# Generated by Django 2.2.16 on 2022-09-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ('id',)},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
