# Generated by Django 2.2.16 on 2022-09-19 12:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_auto_20220919_1649"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="comments",
            options={
                "ordering": ("pub_date",),
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="genres",
            options={
                "ordering": ["name"],
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ("pub_date",),
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AlterModelOptions(
            name="titles",
            options={
                "ordering": ["name"],
                "verbose_name": ("Произведение",),
                "verbose_name_plural": "Произведения",
            },
        ),
        migrations.RemoveConstraint(
            model_name="review",
            name="unique review",
        ),
        migrations.RemoveField(
            model_name="titles",
            name="rating",
        ),
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(
                help_text="Укажите категорию",
                max_length=256,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.SlugField(
                help_text="Укажите уникальный ключ для категории",
                unique=True,
                verbose_name="Уникальный ключ",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата комментария"
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reviews.Review",
                verbose_name="Отзыв",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="text",
            field=models.TextField(verbose_name="Текст комментария"),
        ),
        migrations.AlterField(
            model_name="genres",
            name="name",
            field=models.CharField(
                help_text="Укажите жанр", max_length=256, verbose_name="Жанр"
            ),
        ),
        migrations.AlterField(
            model_name="genres",
            name="slug",
            field=models.SlugField(
                help_text="Укажите уникальный ключ жанра",
                unique=True,
                verbose_name="Уникальный ключ",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата отзыва"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Оценка",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(verbose_name="Текст отзыва"),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="reviews.Titles",
                verbose_name="Произведение",
            ),
        ),
        migrations.AlterField(
            model_name="titles",
            name="category",
            field=models.ForeignKey(
                help_text="Укажите категорию произведения",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="titles",
                to="reviews.Categories",
                verbose_name="Категория произведения",
            ),
        ),
        migrations.AlterField(
            model_name="titles",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Укажите описание произведения",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="titles",
            name="genre",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите жанр произведения",
                related_name="titles",
                to="reviews.Genres",
                verbose_name="Жанр произведения",
            ),
        ),
        migrations.AlterField(
            model_name="titles",
            name="name",
            field=models.CharField(
                help_text="Укажите название произведения",
                max_length=256,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="titles",
            name="year",
            field=models.IntegerField(
                help_text="Укажите год выпуска произведения",
                validators=[django.core.validators.MaxValueValidator(2022)],
                verbose_name="Год выпуска",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("author", "title"), name="unique_review"
            ),
        ),
    ]
